spring.application.name=tasktracker

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

spring.datasource.url=jdbc:postgresql://localhost:5432/taskTrackerr
spring.datasource.username=postgres
spring.datasource.password=Anshima@12290

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=true

# server port (optional)
server.port=9090
